# Generated by Django 6.0.4 on 2026-05-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmotionAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stress_score", models.IntegerField(default=0)),
                ("sadness_score", models.IntegerField(default=0)),
                ("anxiety_score", models.IntegerField(default=0)),
                ("positivity_score", models.IntegerField(default=0)),
                ("emotion", models.CharField(blank=True, max_length=100)),
                ("recommendation", models.CharField(blank=True, max_length=100)),
                ("critical_flags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
