# Generated by Django 6.0.4 on 2026-05-22 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("emotions", "0001_initial"),
        ("journals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emotionanalysis",
            name="journal_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emotion_analysis",
                to="journals.journalentry",
            ),
        ),
    ]
