# Generated by Django 6.0.4 on 2026-05-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BreathingExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("duration_seconds", models.IntegerField()),
                ("rhythm", models.CharField(max_length=100)),
                (
                    "audio_guide",
                    models.FileField(
                        blank=True, null=True, upload_to="breathing/audio/"
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
