# Generated by Django 6.0.4 on 2026-05-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to="journals/audio/"
                    ),
                ),
                ("transcription", models.TextField(blank=True, default="")),
                ("mood", models.CharField(blank=True, default="", max_length=50)),
                ("stress_score", models.IntegerField(blank=True, null=True)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
